global:
  smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
  smtp_from: 'danny.mandel@gmail.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true
  # This is the slack webhook URL.  DO NOT CHECK IN.  Edit on box.
  slack_api_url: 

#route:
#  receiver: 'email-notifications'


route:
  receiver: "slack-notifications"
  routes:
    - receiver: 'email-notifications'
      continue: true
    - receiver: 'slack-notifications'
      continue: true

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - title: "🔥🔥🔥 {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      - text: >-
         {{ range .Alerts -}}
         *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

         *Description:* {{ .Annotations.description }}

         *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
         {{ end }}
      - send_resolved: true

  - name: 'email-notifications'
    email_configs:
      - to: 'danny.mandel@gmail.com'