global:
  smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
  smtp_from: 'danny.mandel@gmail.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true

route:
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'danny.mandel@gmail.com'