global:
  smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
  smtp_from: 'danny.mandel@gmail.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true
  # This is the url to post to #technical
  #slack_api_url:
  # This is the url to post to #alerts-testing
  slack_api_url:

#route:
#  receiver: 'email-notifications'

#receivers:
#  - name: 'email-notifications'
#    email_configs:
#      - to: 'danny.mandel@gmail.com'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - title: "🔥🔥🔥 {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      - text: >-
         {{ range .Alerts -}}
         *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

         *Description:* {{ .Annotations.description }}

         *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
         {{ end }}
      - send_resolved: true