groups:
  - name: iSamples Alert Rules
    rules:

      # Additional alert rules can be defined here
      - alert: PostGres Down
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostGres Instance {{ $labels.instance }} is down"
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'